### ISSUE TITLE
Can't use silk touch pickaxe if another pickaxe of a better material is in the inventory (Tool swap)

### ISSUE THREAD

**Issue by Xoouu** [oliverbravery/Coda#1]
This may not be that much of an issue since the mod is doing what is supposed to, but it is a bit inconvenient. Having a blacklist of enchantments might be a solution (e.g: Do not swap tools with silk touch). 

Pretty cool mod!

**Comment by oliverbravery** [comment]
Feature implemented in "Coda 1.3.1 Beta 1 [1.19.3]".
