### ISSUE TITLE
Suggestion: Auto Eat

### ISSUE THREAD

**Issue by brest21** [oliverbravery/Coda#2]
Suggestion: Auto Eat

I havn't seen this feature outside of hacked clients but a configurable client side auto eat functionality using the offhand food item or when hunger gets to a configurable value. Not sure how possible this is with Coda but worth asking.

Thanks

**Comment by oliverbravery** [comment]
After consideration I have decided that Coda should not have an '_Auto Eat_' feature. In my opinion it crosses the cheat or no cheat line.
